  [env:freenove-s3-uart]
  platform = espressif32 @ ^6.6.0
  board = freenove_esp32_s3_wroom
  framework = arduino

  ; PSRAM helps MP3 decode & HTTPS buffers
  board_build.psram = enabled

  ; Filesystem for settings/playlist, not for the MP3s (we stream)
  board_build.filesystem = littlefs

  monitor_speed = 115200
  upload_speed  = 921600
  monitor_filters = esp32_exception_decoder

  lib_ldf_mode = deep+
  lib_deps =
    bblanchon/ArduinoJson @ ^7.0.4
    madhephaestus/ESP32Servo @ ^1.1.2
    adafruit/Adafruit GFX Library
    adafruit/Adafruit BusIO
    adafruit/Adafruit ST7735 and ST7789 Library
    adafruit/Adafruit GC9A01A
    Bodmer/TJpg_Decoder @ ^1.1.0
    earlephilhower/ESP8266Audio @ 1.9.9
    adafruit/Adafruit NeoPixel


  build_flags =
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_USB_MODE=0
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DUSE_ST7789=0          ; set to 1 if you swap to ST7789 later
    ; -DI2S_BCLK=17 -DI2S_LRCK=15 -DI2S_DOUT=16

  ; If your module has 8MB and you want a larger LittleFS, uncomment:
  ; board_build.partitions = partitions_8mb_singleapp_littlefs.csv
  board_build.partitions = default.csv
